name: Build

on: push

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: test
      BRIDGETOWN_ENV: production
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: yarn

      - name: "Install dependencies with Yarn"
        run: yarn install

      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Build webpack assets
        run: yarn webpack-build

      - name: Test
        run: yarn test
        if: success()